name: Release Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: theypsilon/gcc-arm:10.2-2020.11

    steps:
      - uses: actions/checkout@v4

      - name: Setup rcheevos
        run: cd lib/rcheevos && bash setup.sh

      - name: Build
        run: make

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/MiSTer
          generate_release_notes: true
