name: Release Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup rcheevos
        run: cd lib/rcheevos && bash setup.sh

      - name: Build
        run: docker run --rm -v "${{ github.workspace }}:/work" -w /work theypsilon/gcc-arm:10.2-2020.11 make

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/MiSTer
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
